### PR TITLE
Add missing 'ready' status in the ProgressInfo type

### PR DESCRIPTION
**Pull request by ocavue**
Closes https://github.com/huggingface/transformers.js/issues/1064

### CODE REVIEW

**Comment by pelikhan** [comment]
ProgressInfo needs to be ammended too. 

https://github.com/huggingface/transformers.js/blob/2ee715c672e863edd317324b8feb8522f53342a7/src/utils/core.js#L13

**Comment by ocavue** [comment]
Sorry I'm not following you. What I amended in this PR is exact the `ProgressInfo` type in `src/utils/core.js`.

**Comment by pelikhan** [comment]
My bad! I taught this PR was already merged. Thanks for fixing the issue!

**Review by xenova — APPROVED** [review]
LGTM! ✅

**Pull request merged**
